### ISSUE TITLE
MyDevices library missing

### ISSUE THREAD

**Issue by twasilczyk** [fdufnews/SMART-Response-XE-schematics#3]
I tried to edit schematic, but quite a lot of components are missing. Apparently, you used a custom `MyDevices` library that's not included in the repository.

**Comment by fdufnews** [comment]
I have added the -cache.lib files to the repo

**Comment by twasilczyk** [comment]
Thanks, this helped with opening the project indeed, but now I get a prompt to rescue missing symbols. If I do, then I KiCad modifies the project. If I don't then it drops all of them on any attempt to modify schematic.

**Comment by fdufnews** [comment]
I have not any problem opening the project with only the files on github.
When I open the schematic eeschema asks for 3 symbols substitution that are not in the standard libraries (but present in the cache file)
- 2450FB15001
- ATMEGA128RFA1
- SW_push_small
I accept the substitution, eeschema opens the schematic which is as expected.
When I close eeschema it asks if I want to save the file, I accept.
From now there is no more problem with the files.
The definitions of the symbols in the -cache.lib and the ones in the myDevice.lib are the same.
The -cache.lib file is created to make the project exportable regardless of the configuration of the machine that opens it
