### ISSUE TITLE
Buzzer Schematic Wrong (I think)

### ISSUE THREAD

**Issue by Subsystems-us** [fdufnews/SMART-Response-XE-schematics#6]
When I look at the footprint for the transistor that drives the buzzer, the collector is connected to ground. This had to be a mistake. I searched for an SOT-23 transistor that had the emitter on the side with the single lead and just can't find any. I think the board layout swapped the emitter and the collector and that is why the unit was supplied without a buzzer.
I took a transistor and mounted it upside down and rotated to get the right configuration and it worked great. Did you ever mount a transistor for the buzzer, and if so, what component did you use?

**Comment by fdufnews** [comment]
HI, I mounted a buzzer without the transistor.
I think it is an N-channel mosFET not an NPN BJT.  That why I put one on the schematic and not an NPN for the reason that you explain.
For example some mosFET like this one or equivalent
https://www.onsemi.com/pdf/datasheet/2n7002l-d.pdf

**Comment by Subsystems-us** [comment]
That is what I bought to install. But you can see, if mounted on the board,
pin 3 will be connected to ground. That puts the drain at a higher voltage
than the source and this will conduct continuously through its internal
suppression diode. You would have to use a P-channel or a PNP to get the
right bias from Source to Drain (Collector to Emitter), but then, you could
never turn the transistor on. The base (at 3.3V signal) could
never overcome the battery voltage to forward bias the transistor. The
first FET I installed made a very weak beeping sound when I sent tone
commands. After about an hour, the transistor was fried. I then installed
one upside down and rotated so I kept the same gate, but swapped the drain
and source, and it is nice and loud and has worked for a week now. I really
think this is a board layout issue and they possibly solved it by not
including the speaker in the final product.

**Comment by fdufnews** [comment]
OK, I understand. you are right.

Added a comment in the schematic and in README.md
Updated the pdf of the schematic too
